### ISSUE TITLE
Consider gpu.js for processes with performance bottlenecks

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/buildx-editor#6]
Might be worth looking at https://github.com/gpujs/gpu.js

![screen shot 2017-08-08 at 11 23 46](https://user-images.githubusercontent.com/601961/29069721-fa31f900-7c33-11e7-89f7-62c4a27e2f93.png)

**Comment by jonnor** [comment]
Outside of areas that are trivially massively parallelizable, like pixel-based image processing, writing fast GPU code is much harder than writing fast CPU code. It is also less portable, typically one must support CPU-version in parallel.
I would not recommend going there until one has reached what is possible to achieve on CPU.

**Comment by johnrees** [comment]
Did you look at the docs? It converts regular JS to shaders and automatically falls back to CPU if WebGL isn't available.

I'm cautious about optimising anything prematurely though, just leaving it here as something to maybe think about... eventually

**Comment by jonnor** [comment]
It converts *specially written* JavaScript (direct quote, emphasis mine) to shaders. The compile-able subset does not look to be documented at this time. But for instance it mentions that functions can only take a number and return a number (no objects, arrays, strings). As is common, kernels look to have the same shape input and outputs (because it is mapped onto linear buffers). No mention of data-dependent or thread-index branching for (`if` statements etc), many common limitations around that.

This computational model is basically that of CUDA, with JS as the base language instead of C++. I ported physics algorithms to CUDA in 2010. Optimizing programs on the CPU is generally much more fruitful. But all optimization done before performance analysis is premature.

**Comment by johnrees** [comment]
Understood! I'll close this for now, I think I just got a bit overexcited by the numbers! :)
